
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_presales
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db

  webserver:
    image: nginx:latest
    container_name: nginx_server_presales
    restart: unless-stopped
    ports:
      - "8080:8080"  # ← تغيير المنفذ لـ 8080
    volumes:
      - .:/var/www   # ← إضافة مجلد التطبيق
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # ← إضافة ملف التكوين
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db_presales
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_presales
    restart: always
    ports:
      - "8081:80"  # ← تجنب التعارض مع Nginx
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db  # ← الربط بحاوية قاعدة البيانات
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data: